[build]
  environment = { VITE_API_BASE_URL = "", VITE_KAKAO_JAVASCRIPT_KEY = "e2d3f68bd46dbf577ab999dbb14a7331", VITE_REDIRECT_URI = "https://gbcoco.netlify.app" }

[[redirects]]
  from = "/api/*"
  to = "http://134.185.122.245:8080/api/:splat"
  status = 200
  force = true
